
'use strict';
const VERSION='v28-audited-functional';
const KEYS=['profile','settings','workoutLogs','coachSession','coachHistory','nutritionLogs','favorites','progressLogs','activityLogs','painLogs','supplementLogs','supplementInventory','scaleLogs'];
const $=id=>document.getElementById(id); const today=()=>new Date().toISOString().slice(0,10);
const read=(k,d=[])=>{try{let v=localStorage.getItem(k);return v?JSON.parse(v):d}catch{return d}}; const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); const num=v=>Number.isFinite(Number(v))?Number(v):0;
const workoutPlan={
 monday:{name:'Monday - Upper Body Strength',ex:[['Dumbbell Bench Press',4,8,20,90],['One-Arm Dumbbell Row',4,8,25,75],['Standing Dumbbell Shoulder Press',3,8,15,90],['Reverse Fly',3,12,10,60],['Hammer Curl',3,10,15,60],['Overhead Triceps Extension',3,10,15,60],['Incline Treadmill Walk',1,10,0,0,'minutes']]},
 tuesday:{name:'Tuesday - Lower Body Strength',ex:[['Goblet Squat',4,8,25,90],['Dumbbell Romanian Deadlift',4,8,20,90],['Bulgarian Split Squat',3,8,0,75],['Step-Ups',3,10,0,75],['Standing Calf Raises',3,15,0,45],['Plank',3,30,0,45,'seconds']]},
 wednesday:{name:'Wednesday - Conditioning + Core',ex:[['Stationary Bike Intervals',10,1,0,90,'intervals'],['Plank',3,30,0,45,'seconds'],['Bicycle Crunches',3,15,0,30],['Leg Raises',3,10,0,45],['Mountain Climbers',3,20,0,45]]},
 thursday:{name:'Thursday - Upper Body Hypertrophy',ex:[['Incline Dumbbell Press',4,10,20,75],['One-Arm Dumbbell Row',4,10,25,75],['Arnold Press',3,10,15,75],['Lateral Raise',3,12,10,45],['Dumbbell Fly',3,10,10,60],['Dumbbell Curl',3,12,15,45],['Triceps Extension',3,12,15,45]]},
 friday:{name:'Friday - Lower Body + Conditioning',ex:[['Goblet Squat',4,10,25,75],['Romanian Deadlift',4,10,20,90],['Walking Lunges',3,10,0,75],['Sumo Squat',3,10,25,75],['Calf Raises',3,20,0,45],['Treadmill Intervals',10,1,0,60,'intervals']]}
};
const supplements=[{id:'creatine',name:'Creatine Monohydrate',dose:'5 g daily',time:'8:00 AM or post-workout',why:'Strength, muscle retention, recovery.'},{id:'protein',name:'Protein Powder',dose:'30–40 g as needed',time:'Post-workout or when protein is short',why:'Helps reach daily protein target.'},{id:'pre',name:'Pre-workout',dose:'Optional: 150–250 mg caffeine',time:'30 min before workout',why:'Energy/focus. Avoid late day if sleep suffers.'},{id:'electrolytes',name:'Electrolytes',dose:'1 serving as needed',time:'Before/during sweaty workouts',why:'Hydration support.'},{id:'fishoil',name:'Fish Oil',dose:'1–2 g EPA+DHA/day',time:'With meal',why:'General cardio/joint support.'},{id:'vitd',name:'Vitamin D3',dose:'1,000–2,000 IU if using',time:'Morning with meal',why:'Best guided by bloodwork.'}];
let restTimer=null, lockTimer=null;
function profile(){return read('profile',null)}
function targets(){let p=profile(); if(!p)return {calLow:2400,calHigh:2500,proteinLow:190,proteinHigh:210,goal:195,maintLow:193,maintHigh:197}; let kg=p.weight/2.20462, cm=((p.feet*12)+p.inches)*2.54, b=10*kg+6.25*cm-5*p.age+(p.sex==='female'?-161:p.sex==='male'?5:-78), m=Math.round(b*p.activity), c=Math.max(1200,Math.round((m-400)/50)*50); return {maintenance:m,calLow:c-100,calHigh:c+100,proteinLow:Math.round(Math.min(p.weight,p.goal)*.8),proteinHigh:Math.round(Math.min(p.weight,p.goal)),goal:p.goal,maintLow:p.goal-2,maintHigh:p.goal+2}}
function tab(id){document.querySelectorAll('.tab,nav button').forEach(e=>e.classList.remove('active')); $(id)?.classList.add('active'); document.querySelector(`[data-tab="${id}"]`)?.classList.add('active'); render();}
function init(){document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab)); ['progDate','actDate','painDate','scaleDate'].forEach(id=>{$(id).value=today()}); bind(); populateWorkouts(); if(!profile()&&!localStorage.getItem('profileSkipped'))showProfile(); registerSW(); updateOnline(); window.addEventListener('online',updateOnline); window.addEventListener('offline',updateOnline); resetAutoLock(); ['click','keydown','touchstart'].forEach(e=>document.addEventListener(e,resetAutoLock,{passive:true})); render();}
function bind(){ $('startWorkout').onclick=startSession; $('resumeWorkout').onclick=renderCoach; $('nextEx').onclick=()=>moveEx(1); $('prevEx').onclick=()=>moveEx(-1); $('finishWorkout').onclick=finishSession; $('skipRest').onclick=skipRest; $('addFood').onclick=addFood; $('saveFav').onclick=saveFav; $('saveProgress').onclick=saveProgress; $('saveActivity').onclick=saveActivity; $('savePain').onclick=savePain; $('saveSupps').onclick=saveSupps; $('enableSuppNotifs').onclick=enableSuppNotifs; $('saveInventory').onclick=saveInventory; $('saveScale').onclick=saveScale; $('exportJson').onclick=exportJson; $('importJson').onchange=importJson; $('resetData').onclick=resetData; $('editProfile').onclick=showProfile; $('saveProfile').onclick=saveProfile; $('skipProfile').onclick=()=>{$('onboarding').classList.add('hidden');localStorage.setItem('profileSkipped','1')}; $('voiceEnabled').onchange=saveSettings; $('motivation').onchange=saveSettings; $('testVoice').onclick=()=>speak('Voice coach is ready. Let’s stay consistent.'); $('hideSensitive').onchange=saveSettings; $('savePin').onclick=savePin; $('lockBtn').onclick=lock; $('unlockBtn').onclick=unlock; $('cacheOffline').onclick=cacheOffline;}
function render(){applySettings(); renderHeader(); renderToday(); renderCoach(); renderFood(); renderProgress(); renderActivity(); renderPain(); renderSupplements(); renderWearables(); renderBackupProfile();}
function renderHeader(){let p=profile(),t=targets(); $('title').textContent=p?`${p.name}'s 195 Fitness`:'195 Goal Fitness'; $('phase').innerHTML=p?`Goal: <span data-sensitive>${p.weight} → ${p.goal} lb</span> • Calories <span data-sensitive>${t.calLow}-${t.calHigh}</span> • Protein <span data-sensitive>${t.proteinLow}-${t.proteinHigh}g</span>`:'Complete first-time setup.'}
function metric(title,big,small,level='',sens=false){return `<div class="metric ${level}" ${sens?'data-sensitive':''}><span>${esc(title)}</span><strong>${esc(big)}</strong><small>${esc(small)}</small></div>`}
function renderToday(){let t=targets(), f=todayFood(), p=latestProgress(), a=todayActivity(), s=activeSession(), wk=todayWorkout(); $('todayMetrics').innerHTML=[metric('Workout',s?'Session active':wk.name,s?`${completedSets(s)}/${totalSets(s)} sets`:'Scheduled today'),metric('Calories',`${f.calories}/${t.calHigh}`,'today',f.calories>t.calHigh?'warn':'',true),metric('Protein',`${f.protein}g/${t.proteinLow}g`,'minimum',f.protein>=t.proteinLow?'good':'warn',true),metric('Weight',p?`${p.weight} lb`:'No log',`goal ${t.goal}`, '', true),metric('Steps',a?`${a.steps}`:'No log','goal 8,000',a&&a.steps>=8000?'good':'')].join('')}
function todayWorkout(){let d=new Date().getDay(), keys=['monday','monday','tuesday','wednesday','thursday','friday','monday']; return workoutPlan[keys[d]]}
function populateWorkouts(){let sel=$('workoutSelect'); sel.innerHTML=Object.entries(workoutPlan).map(([k,w])=>`<option value="${k}">${w.name}</option>`).join(''); let d=new Date().getDay(), keys=['monday','monday','tuesday','wednesday','thursday','friday','monday']; sel.value=keys[d]}
function buildSession(key){let w=workoutPlan[key]; return {id:Date.now(),date:today(),name:w.name,startedAt:new Date().toISOString(),idx:0,ex:w.ex.map(x=>({name:x[0],sets:x[1],targetReps:x[2],weight:x[3],rest:x[4],unit:x[5]||'reps',completed:false,skipped:false,pain:false,notes:'',skipReason:'',setsData:Array.from({length:x[1]},(_,i)=>({set:i+1,target:x[2],weight:x[3]||'',reps:'',completed:false}))}))}}
function activeSession(){return read('coachSession',null)} function saveSession(s){write('coachSession',s)} function startSession(){let existing=activeSession(); if(existing&&!confirm('Replace current active session?'))return; let s=buildSession($('workoutSelect').value); saveSession(s); speak(`Starting ${s.name}. Let's get to work.`); render()}
function totalSets(s){return s.ex.reduce((a,e)=>a+e.setsData.length,0)} function completedSets(s){return s.ex.reduce((a,e)=>a+e.setsData.filter(x=>x.completed).length,0)}
function renderCoach(){let s=activeSession(), card=$('exerciseCard'); if(!s){$('sessionStatus').textContent='No active session.'; $('sessionBar').style.width='0%'; card.innerHTML=''; return} let pct=Math.round(completedSets(s)/Math.max(1,totalSets(s))*100); $('sessionStatus').textContent=`${s.name} • ${completedSets(s)}/${totalSets(s)} sets • ${pct}%`; $('sessionBar').style.width=pct+'%'; let e=s.ex[s.idx]; card.innerHTML=`<div class="card"><h3>${esc(e.name)}</h3><p>Target: ${e.sets} × ${e.targetReps} ${e.unit}${e.weight?' @ '+e.weight+' lb':''}</p>${e.setsData.map((sd,i)=>`<div class="setRow ${sd.completed?'completed':''}"><strong>Set ${sd.set}</strong><label>Weight<input data-w="${i}" type="number" step="0.5" value="${esc(sd.weight)}"></label><label>${e.unit}<input data-r="${i}" type="number" value="${esc(sd.reps)}" placeholder="${sd.target}"></label><button onclick="toggleSet(${i})">${sd.completed?'Undo':'Done'}</button></div>`).join('')}<label><input id="exPain" type="checkbox" ${e.pain?'checked':''}> Pain/discomfort</label><label>Notes<textarea id="exNotes">${esc(e.notes)}</textarea></label><label>Skip reason<input id="skipReason" value="${esc(e.skipReason)}"></label><button onclick="skipExercise()" class="ghost">${e.skipped?'Unskip':'Skip'} Exercise</button><button onclick="completeExercise()">${e.completed?'Mark Incomplete':'Mark Exercise Complete'}</button></div>`; card.querySelectorAll('input[data-w],input[data-r]').forEach(inp=>inp.onchange=storeSetInputs); $('exPain').onchange=()=>{let ss=activeSession();ss.ex[ss.idx].pain=$('exPain').checked;saveSession(ss); if($('exPain').checked){speak('Pain detected. Stop and assess. Pain is not the goal.');}}; $('exNotes').onchange=()=>{let ss=activeSession();ss.ex[ss.idx].notes=$('exNotes').value;saveSession(ss)}; $('skipReason').onchange=()=>{let ss=activeSession();ss.ex[ss.idx].skipReason=$('skipReason').value;saveSession(ss)}; renderProgression();}
function storeSetInputs(){let s=activeSession(), e=s.ex[s.idx]; document.querySelectorAll('[data-w]').forEach(i=>e.setsData[num(i.dataset.w)].weight=i.value); document.querySelectorAll('[data-r]').forEach(i=>e.setsData[num(i.dataset.r)].reps=i.value); saveSession(s)}
window.toggleSet=i=>{let s=activeSession(), e=s.ex[s.idx]; storeSetInputs(); s=activeSession(); e=s.ex[s.idx]; let sd=e.setsData[i]; sd.completed=!sd.completed; if(sd.completed&&!sd.reps)sd.reps=sd.target; e.completed=e.setsData.every(x=>x.completed); saveSession(s); render(); if(sd.completed){speak(coachPhrase('set')); startRest(e.rest||num($('restDefault').value)||60)}}
function startRest(sec){clearInterval(restTimer); let left=sec; $('restBox').classList.remove('hidden'); const draw=()=>{$('restText').textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`}; draw(); restTimer=setInterval(()=>{left--; if([60,30,10].includes(left))speak(`${left} seconds remaining.`); draw(); if(left<=0){skipRest(); speak('Rest complete. Prepare for your next set.'); if(navigator.vibrate)navigator.vibrate([150,80,150]);}},1000)}
function skipRest(){clearInterval(restTimer); $('restBox').classList.add('hidden')} function moveEx(d){let s=activeSession(); if(!s)return; s.idx=Math.max(0,Math.min(s.ex.length-1,s.idx+d)); saveSession(s); render()} window.skipExercise=()=>{let s=activeSession(), e=s.ex[s.idx]; e.skipped=!e.skipped; e.skipReason=$('skipReason').value; saveSession(s); render()} ; window.completeExercise=()=>{let s=activeSession(), e=s.ex[s.idx]; storeSetInputs(); s=activeSession(); e=s.ex[s.idx]; e.completed=!e.completed; if(e.completed)e.setsData.forEach(x=>{x.completed=true;if(!x.reps)x.reps=x.target}); saveSession(s); render()}
function finishSession(){let s=activeSession(); if(!s)return; s.finishedAt=new Date().toISOString(); s.duration=Math.round((new Date(s.finishedAt)-new Date(s.startedAt))/60000); let hist=read('coachHistory'); hist.unshift(s); write('coachHistory',hist); let logs=read('workoutLogs'); logs.unshift({date:s.date,workout:s.name,duration:s.duration,completedSets:completedSets(s),totalSets:totalSets(s),exercises:s.ex}); write('workoutLogs',logs); localStorage.removeItem('coachSession'); $('sessionSummary').innerHTML=`<div class="metric good"><strong>Workout complete</strong><small>${completedSets(s)}/${totalSets(s)} sets in ${s.duration} min</small></div>`; speak('Workout complete. Excellent work today. Recovery and nutrition are next.'); render()}
function renderProgression(){let box=$('progressionBox'), hist=read('coachHistory'), rec=[]; let names={}; hist.forEach(sess=>sess.ex.forEach(e=>{(names[e.name]||(names[e.name]=[])).push(e)})); Object.entries(names).forEach(([n,arr])=>{let last=arr.slice(0,2); if(last.length<2)return; let good=last.every(e=>e.completed&&!e.pain&&!e.skipped&&e.setsData.every(s=>s.completed&&num(s.reps)>=num(s.target))); if(good){let w=num(last[0].setsData[0].weight); if(w)rec.push(`<div class="metric good"><strong>${esc(n)}</strong><small>All targets hit twice. Try ${w+(n.toLowerCase().match(/squat|deadlift|lunge/)?10:5)} lb next time.</small></div>`)} }); box.innerHTML=rec.join('')||'<p class="muted">No increases yet. Hit all reps twice with no pain flags.</p>'}
function coachPhrase(type){let s=read('settings',{}); let high=s.motivation==='High'; return type==='set'?(high?'Great set. Stay locked in.':'Great work. Get ready for the next set.'):'You have got this.'} function speak(text){let s=read('settings',{}); if(!s.voice||!('speechSynthesis'in window))return; speechSynthesis.cancel(); speechSynthesis.speak(new SpeechSynthesisUtterance(text));}
function addFood(){let f={date:today(),meal:$('meal').value,name:$('foodName').value.trim()||'Food',calories:num($('foodCal').value),protein:num($('foodProtein').value),carbs:num($('foodCarbs').value),fat:num($('foodFat').value)}; if(f.calories<0||f.protein<0)return alert('Invalid negative values.'); let logs=read('nutritionLogs'); logs.unshift(f); write('nutritionLogs',logs); ['foodName','foodCal','foodProtein','foodCarbs','foodFat'].forEach(id=>$(id).value=''); render()}
function saveFav(){let f={meal:$('meal').value,name:$('foodName').value.trim(),calories:num($('foodCal').value),protein:num($('foodProtein').value),carbs:num($('foodCarbs').value),fat:num($('foodFat').value)}; if(!f.name)return alert('Enter food name.'); let fav=read('favorites'); fav.unshift(f); write('favorites',fav.slice(0,30)); render()}
function renderFood(){let logs=read('nutritionLogs').filter(f=>f.date===today()); $('foodLog').innerHTML=logs.map(f=>`<p data-sensitive><strong>${esc(f.name)}</strong> — ${f.calories} cal, ${f.protein}g protein</p>`).join('')||'<p class="muted">No food logged today.</p>'; let fav=read('favorites'); $('favorites').innerHTML=fav.map((f,i)=>`<div class="metric"><strong>${esc(f.name)}</strong><small>${f.calories} cal • ${f.protein}g</small><button onclick="repeatFav(${i})">Add</button></div>`).join('')||'<p class="muted">No favorites.</p>'} window.repeatFav=i=>{let f=read('favorites')[i]; if(f){let l=read('nutritionLogs'); l.unshift({...f,date:today()}); write('nutritionLogs',l); render()}}
function todayFood(){return read('nutritionLogs').filter(f=>f.date===today()).reduce((a,f)=>({calories:a.calories+num(f.calories),protein:a.protein+num(f.protein)}),{calories:0,protein:0})}
function saveProgress(){let w=num($('progWeight').value); if(w<=0)return alert('Enter weight.'); let l=read('progressLogs'); l.unshift({date:$('progDate').value||today(),weight:w,waist:num($('progWaist').value),notes:$('progNotes').value}); write('progressLogs',l); render();}
function latestProgress(){return read('progressLogs').sort((a,b)=>b.date.localeCompare(a.date))[0]} function renderProgress(){let rows=read('progressLogs').slice().sort((a,b)=>a.date.localeCompare(b.date)); draw('weightChart',[{label:'Weight',pts:rows.map(r=>[r.date,num(r.weight)])}],targets().goal)}
function saveActivity(){let l=read('activityLogs'); l.unshift({date:$('actDate').value||today(),steps:num($('steps').value),active:num($('activeMin').value),cardio:num($('cardioMin').value),sleep:num($('sleep').value),rhr:num($('rhr').value),source:'manual'}); write('activityLogs',l); render()}
function todayActivity(){return read('activityLogs').find(a=>a.date===today())} function renderActivity(){let a=todayActivity(), msgs=[]; if(!a)msgs.push(metric('Start tracking','No activity logged','Add steps/sleep/RHR','warn')); else {msgs.push(metric('Steps',a.steps,'goal 8,000',a.steps>=8000?'good':'warn')); msgs.push(metric('Sleep',a.sleep+' h','goal 7+',a.sleep>=7?'good':'warn')); if(a.sleep&&a.sleep<6)msgs.push(metric('Recovery','Low sleep','Consider reducing intensity','warn')); if(a.rhr)msgs.push(metric('Resting HR',a.rhr,'watch elevated trends'))} $('recoveryBox').innerHTML=msgs.join('')}
function savePain(){let p={date:$('painDate').value||today(),exercise:$('painExercise').value,location:$('painLocation').value,side:$('painSide').value,type:$('painType').value,severity:num($('painSeverity').value),timing:$('painTiming').value,symptoms:$('painSymptoms').value,action:$('painAction').value}; p.recommendation=painRec(p); let l=read('painLogs'); l.unshift(p); write('painLogs',l); speak(p.recommendation.voice); render()}
function painRec(p){let high=/(chest|pressure|dizziness|shortness|breath|faint|numb|radiating|weakness)/i.test([p.location,p.type,p.symptoms].join(' ')); if(high||p.severity>=8)return {level:'bad',text:'Stop the workout. Do not push through this. Consider urgent medical evaluation, especially with chest pressure, dizziness, breathing trouble, weakness, numbness, or radiating pain.',voice:'Pain warning. Stop the workout and assess. Pain is not the goal.'}; if(p.type==='Sharp'||p.severity>=4)return {level:'warn',text:'Modify: stop this exercise, reduce weight 10–20%, use a substitute, and block weight increases for this movement.',voice:'Pain detected. Reduce weight or substitute the exercise.'}; return {level:'good',text:'Monitor: mild soreness/fatigue may be normal. Keep form strict and reassess next set.',voice:'Monitor this. Keep form controlled.'}}
function renderPain(){let l=read('painLogs'); let last=l[0]; $('painRecommendation').innerHTML=last?`<div class="metric ${last.recommendation.level}"><strong>${esc(last.location)} pain: ${esc(last.type)} ${last.severity}/10</strong><small>${esc(last.recommendation.text)}</small></div>`:'<p class="muted">No pain logged.</p>'; $('painHistory').innerHTML=l.slice(0,10).map(p=>`<p><strong>${esc(p.date)} ${esc(p.location)}</strong> ${p.severity}/10 — ${esc(p.recommendation.text)}</p>`).join('')}
function renderSupplements(){let t=targets(), log=read('supplementLogs').find(x=>x.date===today())||{}; $('suppPlan').innerHTML=supplements.map(s=>`<div class="metric"><strong>${s.name}</strong><small>${s.dose}<br>${s.time}<br>${s.why}</small></div>`).join(''); $('suppChecks').innerHTML=supplements.map(s=>`<label class="metric"><input type="checkbox" data-supp="${s.id}" ${log[s.id]?'checked':''}> <strong>${s.name}</strong><small>${s.dose}</small></label>`).join('')+`<div class="metric"><strong>Protein Goal</strong><small>${t.proteinLow}-${t.proteinHigh}g/day</small></div>`; let inv=read('supplementInventory',{}); ['Creatine','Protein','Pre','Fish','D'].forEach(k=>{let el=$('inv'+k); if(el&&!el.value)el.value=inv[k.toLowerCase()]||''})}
function saveSupps(){let entry={date:today()}; document.querySelectorAll('[data-supp]').forEach(c=>entry[c.dataset.supp]=c.checked); let logs=read('supplementLogs').filter(x=>x.date!==today()); logs.unshift(entry); write('supplementLogs',logs); speak('Supplements logged. Consistency supports your training.'); render()} function saveInventory(){let inv={creatine:num($('invCreatine').value),protein:num($('invProtein').value),pre:num($('invPre').value),fish:num($('invFish').value),d:num($('invD').value)}; write('supplementInventory',inv); alert('Inventory saved.')} async function enableSuppNotifs(){if(!('Notification'in window))return alert('Notifications not supported. Use the included supplement-reminders.ics file.'); let p=await Notification.requestPermission(); if(p==='granted')new Notification('Supplement reminders enabled',{body:'Use Calendar file for most reliable iPhone reminders.'})}
function saveScale(){let w=num($('scaleWeight').value); if(w<=0)return alert('Enter weight.'); let entry={date:$('scaleDate').value||today(),source:$('scaleSource').value,weight:w,bodyFat:num($('scaleFat').value),muscle:num($('scaleMuscle').value)}; let s=read('scaleLogs'); s.unshift(entry); write('scaleLogs',s); let p=read('progressLogs'); p.unshift({date:entry.date,weight:w,waist:'',notes:`${entry.source}; body fat ${entry.bodyFat||'-'}%; muscle ${entry.muscle||'-'}`}); write('progressLogs',p); render()} function renderWearables(){}
function showProfile(){let p=profile()||{name:'',age:48,sex:'male',feet:6,inches:2,weight:215,goal:195,activity:1.55}; $('pName').value=p.name; $('pAge').value=p.age; $('pSex').value=p.sex; $('pFeet').value=p.feet; $('pInches').value=p.inches; $('pWeight').value=p.weight; $('pGoal').value=p.goal; $('pActivity').value=p.activity; $('onboarding').classList.remove('hidden')} function saveProfile(){let p={name:$('pName').value.trim()||'User',age:num($('pAge').value),sex:$('pSex').value,feet:num($('pFeet').value),inches:num($('pInches').value),weight:num($('pWeight').value),goal:num($('pGoal').value),activity:num($('pActivity').value)}; if(!p.age||!p.weight||!p.goal)return $('profileErr').textContent='Enter age, weight and goal.'; write('profile',p); $('onboarding').classList.add('hidden'); render()} function renderBackupProfile(){let p=profile(); $('profileSummary').innerHTML=p?`<table><tr><td>Name</td><td>${esc(p.name)}</td></tr><tr><td>Age</td><td>${p.age}</td></tr><tr><td>Weight goal</td><td data-sensitive>${p.weight} → ${p.goal}</td></tr></table>`:'No profile.'}
function settings(){return read('settings',{})} function saveSettings(){let s=settings(); s.voice=$('voiceEnabled').checked; s.motivation=$('motivation').value; s.hideSensitive=$('hideSensitive').checked; write('settings',s); applySettings()} function applySettings(){let s=settings(); document.body.classList.toggle('hideSensitive',!!s.hideSensitive); if($('voiceEnabled'))$('voiceEnabled').checked=!!s.voice; if($('motivation'))$('motivation').value=s.motivation||'Moderate'; if($('hideSensitive'))$('hideSensitive').checked=!!s.hideSensitive; $('onlineStatus')&&($('onlineStatus').textContent=navigator.onLine?'Online':'Offline')}
async function hash(v){if(crypto.subtle){let b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}return btoa(v)} async function savePin(){let pin=$('pinSet').value; if(pin.length<4)return alert('Use at least 4 characters.'); let s=settings(); s.pin=await hash(pin); write('settings',s); $('pinSet').value=''; alert('PIN saved.')} function lock(){if(settings().pin)$('lockScreen').classList.remove('hidden')} async function unlock(){let s=settings(); if(await hash($('unlockPin').value)===s.pin){$('unlockErr').textContent='';$('lockScreen').classList.add('hidden')}else $('unlockErr').textContent='Wrong PIN'} function resetAutoLock(){clearTimeout(lockTimer); let s=settings(); if(s.pin&&s.autoLock)lockTimer=setTimeout(lock,s.autoLock*60000)}
function backup(){let data={app:'195 Goal Fitness',version:VERSION,exportedAt:new Date().toISOString(),data:{}}; KEYS.forEach(k=>data.data[k]=read(k,k==='profile'?null:[])); return data} function download(n,t,type='text/plain'){let b=new Blob([t],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;a.click();URL.revokeObjectURL(u)} function exportJson(){download(`fitness-backup-${today()}.json`,JSON.stringify(backup(),null,2),'application/json')} function importJson(e){let f=e.target.files[0]; if(!f)return; let r=new FileReader(); r.onload=()=>{try{let b=JSON.parse(r.result); if(!b.data)throw Error(); if(confirm('Replace local app data with this backup?')){Object.entries(b.data).forEach(([k,v])=>write(k,v)); location.reload()}}catch{alert('Invalid backup.')}}; r.readAsText(f)} function resetData(){if(confirm('Export a backup first. Reset local data?')&&confirm('Final confirmation. This cannot be undone.')){KEYS.forEach(k=>localStorage.removeItem(k));location.reload()}}
function exportCsv(key){let rows=read(key); if(!rows.length)return alert('No data.'); let heads=[...new Set(rows.flatMap(r=>Object.keys(r)))]; let csv=[heads.join(','),...rows.map(r=>heads.map(h=>`"${String(typeof r[h]==='object'?JSON.stringify(r[h]):r[h]??'').replace(/"/g,'""')}"`).join(','))].join('\n'); download(`${key}.csv`,csv,'text/csv')} async function cacheOffline(){if(!('caches'in window))return alert('Caching unavailable.'); let c=await caches.open('fitness-v28'); await c.addAll(['./','index.html','app.js','styles.css','manifest.json','service-worker.js','icon.svg','supplement-reminders.ics']); alert('Saved for offline use.')} function updateOnline(){if($('onlineStatus'))$('onlineStatus').textContent=navigator.onLine?'Online':'Offline'} async function registerSW(){if('serviceWorker'in navigator)try{await navigator.serviceWorker.register('service-worker.js')}catch(e){console.warn(e)}}
function draw(id,series,goal){let c=$(id); if(!c)return; let ctx=c.getContext('2d'),W=c.width,H=c.height,pad=42; ctx.clearRect(0,0,W,H); ctx.font='12px system-ui'; let pts=series.flatMap(s=>s.pts).filter(p=>Number.isFinite(p[1])); if(!pts.length){ctx.fillText('No data yet.',pad,H/2);return} let xs=[...new Set(pts.map(p=>p[0]))].sort(), vals=pts.map(p=>p[1]); if(goal)vals.push(goal); let min=Math.min(...vals),max=Math.max(...vals); if(min===max){min--;max++} let xf=x=>pad+(xs.indexOf(x)/Math.max(1,xs.length-1))*(W-pad*1.5), yf=y=>H-pad-((y-min)/(max-min))*(H-pad*1.5); ctx.globalAlpha=.35; ctx.beginPath(); ctx.moveTo(pad,20);ctx.lineTo(pad,H-pad);ctx.lineTo(W-20,H-pad);ctx.stroke();ctx.globalAlpha=1; series.forEach(s=>{let p=s.pts;ctx.beginPath();p.forEach((pt,i)=>{let x=xf(pt[0]),y=yf(pt[1]);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillText(s.label,W-150,24)}); if(goal){let y=yf(goal);ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(W-20,y);ctx.stroke();ctx.setLineDash([]);ctx.fillText('Goal '+goal,W-90,y-6)}}
init();
